### ISSUE TITLE
Error: Unable to accept connection to server socket: Interrupted system call

### ISSUE THREAD

**Issue by serra82** [mikejuni/OpenWRT-ShairPort#1]
I have this error, any idea?
Thank you

root@OpenWrt:~#  shairport -a alpha -b 320 -o 5002 --alsa_pcm=default --alsa_ctl=default --alsa_volume=Speaker
LogLevel: 1
AirName: alpha
HWID: ?B!7Bv
HWID_Hex(12): 003F42213742
Established under name '003F42213742@alpha'
*********\* RECV OPTIONS **********
Fixed value: [dsd53qH5T0k4E/oEP7vd3w==]
Error: Unable to accept connection to server socket: Interrupted system call
*********\* RECV ANNOUNCE **********
Fixed value: [jqo0vr/mGPmVCWf6bVoNjw==]
Fixed value: [b3FOMXIZ77j7MdADMW10iFGq9uLpHdxJCUFB3xkEAKTkqOyKxhzkhVKi4rtMxYAz9fJydXsIbyX+Uhk6C5odQWl2fXRV6yI671kdoSAOy+X7iKA8vs4qScjITepb39ZiQPO7D6/prjlPhCPf/l5UKjhDf4ZfglEuNl6ZdconnHSpf8M1mjCAjoYcMrWMv8LnsvJee5xvuWiCkt3J1YN7WS7SU1YPvunbK8c6gRbyQpGgoR99soMPg+3EBKwgKMdiVbybGc6J7wNTgNEbdeVpWmV3RIr7NanlNJbwXRQ/R9M4rpfS15bzRKfCvuORIhBwAWhK+Gwoyyk3yxxA/0yJqg==]
*********\* RECV SETUP **********
ALSA: audio_set_driver: this sets the PCM device to :default
ALSA: audio_set_device_name: this sets the output in mixer to :Speaker
ALSA: audio_set_device_id: this sets the mixer control device to :default
ALSA: Sample rate proposed 44100*********\* RECV RECORD **********

*********\* RECV SET_PARAMETER **********
*********\* RECV SET_PARAMETER **********
ALSA: Sample rate gotten 44100
ALSA: Use ALSA Mixer rather than soft manupulating volume
shairport: simple.c: 282: snd_mixer_selem_get_playback_volume_range: Assertion `elem' failed.
Error: Unable to accept connection to server socket: Interrupted system call

**Comment by mikejuni** [comment]
The --alsa_volume flag does not point to a right volume output.

Execute alsamixer (in OpenWRT, you need to install alsa-utils package) and find out which volume output to specify to and set it correctly. Sometimes it may be called "Master" or "Front". Please note that it is case-sensitive.

Rgds

**Comment by serra82** [comment]
Thank you
